import assert from "node:assert/strict";
import test from "node:test";
import {
  mergeRootReadme,
  normalizeLanguage,
  problemPath,
  renderProblemReadme,
  renderRootReadme,
  ROOT_END,
  ROOT_START
} from "../extension/templates.js";

const settings = { rootDir: "LeetCode" };

function twoSum() {
  return {
    number: "1",
    title: "Two Sum",
    slug: "two-sum",
    url: "https://leetcode.com/problems/two-sum/",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    language: "Python3",
    extension: "py",
    code: "class Solution: pass",
    description: "Given an array of integers.",
    acceptedAt: "2024-01-01T00:00:00.000Z",
    timeSpent: "3m 20s",
    attemptsSummary: "1st try (Clean AC)"
  };
}

test("renderRootReadme emits a delimited block that lists every problem", () => {
  const readme = renderRootReadme([twoSum()], settings);
  assert.ok(readme.startsWith(ROOT_START));
  assert.ok(readme.trimEnd().endsWith(ROOT_END));
  assert.match(readme, /\[Two Sum\]\(\.\/0001-two-sum\/README\.md\)/);
  assert.match(readme, /### Array \(1\)/);
});

test("renderRootReadme skips incomplete records", () => {
  const readme = renderRootReadme([{ number: "1", language: "Go" }], settings);
  assert.doesNotMatch(readme, /Two Sum/);
  assert.match(readme, /No synced problems yet/);
});

test("mergeRootReadme creates a new file when the repository has none", () => {
  const generated = renderRootReadme([twoSum()], settings);
  const merged = mergeRootReadme("", generated);
  assert.equal(merged.trim(), generated.trim());
});

test("mergeRootReadme keeps content written by the user around the generated block", () => {
  const existing = `# My archive\n\nHand written intro.\n\n${ROOT_START}\nold generated\n${ROOT_END}\n\n## Footer kept\n`;
  const generated = `${ROOT_START}\nnew generated\n${ROOT_END}`;
  const merged = mergeRootReadme(existing, generated);

  assert.match(merged, /^# My archive/);
  assert.match(merged, /Hand written intro\./);
  assert.match(merged, /new generated/);
  assert.doesNotMatch(merged, /old generated/);
  assert.match(merged, /## Footer kept/);
  assert.equal(merged.split(ROOT_START).length, 2, "only one generated block");
});

test("mergeRootReadme replaces a README generated by older versions", () => {
  const legacy = `# LeetCode Solutions\n\n> Generated by LeetFlow Sync. Solve on LeetCode, keep the archive on GitHub.\n\nold rows\n\n<!-- LEETFLOW:END -->\n`;
  const generated = `${ROOT_START}\nfresh\n${ROOT_END}`;
  const merged = mergeRootReadme(legacy, generated);
  assert.equal(merged.trim(), generated.trim());
});

test("mergeRootReadme appends the block below a hand written README", () => {
  const existing = "# Solutions I wrote by hand\n\nSome notes.\n";
  const generated = `${ROOT_START}\nindex\n${ROOT_END}`;
  const merged = mergeRootReadme(existing, generated);
  assert.match(merged, /^# Solutions I wrote by hand/);
  assert.match(merged, /index/);
});

test("problemPath and renderProblemReadme produce the generated layout", () => {
  const problem = twoSum();
  assert.equal(problemPath(problem, settings), "LeetCode/0001-two-sum");
  const readme = renderProblemReadme(problem, settings);
  assert.match(readme, /# \[1\. Two Sum\]\(https:\/\/leetcode\.com\/problems\/two-sum\/\)/);
  assert.match(readme, /\[`two-sum\.py`\]\(\.\/two-sum\.py\)/);
  assert.match(readme, /Array/);
});

test("normalizeLanguage keeps a single shared mapping", () => {
  assert.deepEqual(normalizeLanguage("python3"), { name: "Python3", ext: "py" });
  assert.deepEqual(normalizeLanguage("C++"), { name: "C++", ext: "cpp" });
  assert.deepEqual(normalizeLanguage("golang"), { name: "Go", ext: "go" });
  assert.deepEqual(normalizeLanguage("unknown"), { name: "unknown", ext: "txt" });
  assert.equal(normalizeLanguage("").name, "Unknown");
});
