import { execFile } from "node:child_process";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const root = dirname(fileURLToPath(import.meta.url));
const source = join(root, "extension");
const dist = join(root, "dist");
const sharedFiles = [
  "content.js", "content.css", "inpage.js", "github.js", "options.css", "options.html", "options.js",
  "popup.css", "popup.html", "popup.js", "review.js", "roadmaps.js", "storage.js", "templates.js"
];

async function cleanDir(path) {
  await rm(path, { recursive: true, force: true });
  await mkdir(path, { recursive: true });
}

function stripModuleSyntax(sourceText) {
  return sourceText
    .replace(/^import .*?;\s*$/gm, "")
    .replace(/^export\s+(?=(async\s+)?function|const|let|var|class)/gm, "")
    .replace(/^export\s*\{[^}]+\};?\s*$/gm, "");
}

async function zipDirectory(sourceDir, outZipPath) {
  try {
    await rm(outZipPath, { force: true });
    await execFileAsync("zip", ["-r", "-q", outZipPath, "."], { cwd: sourceDir });
  } catch (err) {
    console.warn(`Zip packaging skipped for ${sourceDir}: ${err.message}`);
  }
}

async function writePackage(name, manifestName, backgroundName) {
  const output = join(dist, name);
  await cleanDir(output);
  const manifest = await readFile(join(source, manifestName));
  await writeFile(join(output, "manifest.json"), manifest);
  for (const file of sharedFiles) {
    await cp(join(source, file), join(output, file));
  }
  if (backgroundName === "background.js") {
    await cp(join(source, "background.js"), join(output, "background.js"));
  } else {
    const modules = ["storage.js", "github.js", "roadmaps.js", "templates.js", "review.js", "background.js"];
    const contents = [];
    for (const file of modules) {
      contents.push(`/* ${file} */\n${stripModuleSyntax(await readFile(join(source, file), "utf8"))}`);
    }
    await writeFile(join(output, backgroundName), contents.join("\n\n"));
  }
  await writeFile(join(output, ".source"), "Generated by build.mjs\n");
}

await writePackage("chrome", "manifest.chrome.json", "background.js");
await writePackage("firefox", "manifest.firefox.json", "background.firefox.js");

await zipDirectory(join(dist, "chrome"), join(dist, "leetflow-chrome.zip"));
await zipDirectory(join(dist, "firefox"), join(dist, "leetflow-firefox.zip"));

console.log("Built dist/chrome, dist/firefox, and zip packages.");
