import { execFile } from "node:child_process";
import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const root = dirname(fileURLToPath(import.meta.url));
const source = join(root, "extension");
const dist = join(root, "dist");
const EXCLUDED = new Set([
  "manifest.json",
  "manifest.chrome.json",
  "manifest.firefox.json",
  "README.md"
]);
const GITHUB_ID = "leetflow-sync@vincentlalo-long.github.io";

function firefoxManifest(base) {
  const manifest = structuredClone(base);
  manifest.background = { scripts: ["background.js"], type: "module" };
  manifest.browser_specific_settings = {
    gecko: {
      id: GITHUB_ID,
      strict_min_version: "142.0",
      data_collection_permissions: { required: ["websiteContent"] }
    },
    gecko_android: {
      strict_min_version: "142.0"
    }
  };
  return manifest;
}

async function listFiles(directory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...(await listFiles(join(directory, entry.name), relativePath)));
    } else {
      files.push(relativePath);
    }
  }
  return files;
}

async function copySourceFiles(target) {
  const files = await listFiles(source);
  for (const file of files) {
    if (EXCLUDED.has(file)) continue;
    const destination = join(target, file);
    await mkdir(dirname(destination), { recursive: true });
    await cp(join(source, file), destination);
  }
}

async function checkSyntax(directory) {
  const files = (await listFiles(directory)).filter((file) => file.endsWith(".js"));
  for (const file of files) {
    await execFileAsync(process.execPath, ["--check", join(directory, file)]);
  }
  return files.length;
}

async function cleanDirectory(path) {
  await rm(path, { recursive: true, force: true });
  await mkdir(path, { recursive: true });
}

async function archive(sourceDir, output) {
  await rm(output, { force: true });
  await execFileAsync("zip", ["-r", "-q", output, "."], { cwd: sourceDir });
}

async function writePackage(name, manifest) {
  const output = join(dist, name);
  await cleanDirectory(output);
  await writeFile(join(output, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  await copySourceFiles(output);
  await writeFile(
    join(output, ".source"),
    `Generated by build.mjs from extension/ — do not edit. Version ${manifest.version}.\n`
  );
  const checked = await checkSyntax(output);
  console.log(`Built dist/${name} (${checked} scripts syntax-checked).`);
  return output;
}

const packageJson = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
const baseManifest = JSON.parse(await readFile(join(source, "manifest.json"), "utf8"));
baseManifest.version = packageJson.version;

await cleanDirectory(dist);
const chromeDir = await writePackage("chrome", structuredClone(baseManifest));
const firefoxDir = await writePackage("firefox", firefoxManifest(baseManifest));

await archive(chromeDir, join(dist, "leetflow-chrome.zip"));
await archive(firefoxDir, join(dist, "leetflow-firefox.xpi"));

console.log("Built dist/chrome, dist/firefox, dist/leetflow-chrome.zip, dist/leetflow-firefox.xpi.");
